### PR TITLE
Typo in pom

### PR DESCRIPTION
**Pull request by nmervaillie**
Removed "distribution" classifier to build. See #2

### CODE REVIEW

**Comment by obfischer** [comment]
Interesting. It works on our CI server as it is, but not one my local machine...

**Comment by obfischer** [comment]
Ok. I found the causing change after I removed my local Maven cache.

**Comment by obfischer** [comment]
Thanks for your PR. It helped us to detect other problems where we are not sure if it is a configuration or Maven problem.

**Comment by nmervaillie** [comment]
thanks

**Pull request merged**
